# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 860b16ee07fff30a3a88b00fd4222a72f3ea1997b85b7e585199702fad0e599c518f95add7630f73a45399b58fd896879552439fc5795fa75220d5c3c6ef13d5

test:
  secret_key_base: 8388988c717440abf5e48a747de588654d9a7daf3cfc554b79288504d921042e3dde581c3bd3bd683895910a16f952f4676e0676e6c9d6a21018a6e0dc26391e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
